sudo: false
language: node_js

node_js:
  - "8"

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn run lint
  - yarn run examples:lint
  - yarn test
  
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages

notifications:
  email:
    on_success: never
    on_failure: never
